server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cvnest"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: elastic

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: capybuk@gmail.com
    password: kqeiimopnbdqrlwj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ=="
  access-token-validity-in-seconds: 864000
  refresh-token-validity-in-seconds: 864000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

cloudinary:
  cloud-name: dcpz6bqyl
  api-key: 832475981822277
  api-secret: 0hn_kdhvvll9Iaw-8dijdJ4xYZQ

