server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cvnest"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      port: 6379
      host: localhost

  mail:
    host: smtp.gmail.com
    port: 587
    username: capybuk@gmail.com
    password: kqeiimopnbdqrlwj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ=="
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 864000

